name: Generate Web Content

on:
  push:
    branches: [ main ]
  issues:
    types: [opened, edited, labeled, unlabeled, deleted, closed, reopened]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore .\src\DumpExam\DumpExam.csproj
    - name: Build
      run: dotnet build .\src\DumpExam\DumpExam.csproj --no-restore
    - name: Execute app to generate web content
      working-directory: .\src\DumpExam\bin\Debug\net5.0
      run: Start-Process -FilePath "DumpExam.exe"
    - name: Commit web content
      run: |
        git config --global user.name 'VanDng'
        git config --global user.email 'VanDng@users.noreply.github.com'
        git add -A -- .\docs
        git commit -m "[GitAction] Commit All Changes in the folder Docs" -- .\docs
        git push
